name: hugo-deploy-CI
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # step1 拉代码
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      # step2 构建环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      # step3 构建
      - name: Build
        run: hugo
      # step4 发布
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: liangweidonggood/liangweidonggood.github.io
          publish_dir: ./public
          publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}
